name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # installs rust toolchain/rustup
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          # or nightly
          toolchain: stable
          # override current directory
          override: true
      - uses: actions-rs/cargo@v1
        with:
          # calls 'cargo test'
          command: test

  fmt:
    name: RustFmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          # install specific part of toolchain
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          # when un-formatted code prints in console and fails it
          # runs 'cargo fmt --all -- --check'
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          # rust linter
          components: clippy
      - uses: actions-rs/clippy-check@v1
        with:
          # fail linting if there is any warnings
          # runs 'cargo clippy -- -D warnings'
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings


  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run cargo-tarpaulin
        # crate https://lib.rs/crates/cargo-tarpaulin
        # runs 'cargo tarpaulin --ignore-tests'
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: '--ignore-tests'
      - name: Codecov
        uses: codecov/codecov-action@v2